using System;
using Microsoft.Xrm.Sdk;

namespace D365.Plugins
{
    public class AccountCreatePlugin : IPlugin
    {
        private const string DescriptionAttribute = "description";
        private const string DescriptionText = "This is a test description generated by Plugin";

        public void Execute(IServiceProvider serviceProvider)
        {
            if (serviceProvider == null) throw new ArgumentNullException(nameof(serviceProvider));

            var tracing = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
            tracing?.Trace("AccountCreatePlugin: Enter Execute");

            var context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
            if (context == null) return;

            if (!string.Equals(context.MessageName, "Create", StringComparison.OrdinalIgnoreCase)) return;
            if (!string.Equals(context.PrimaryEntityName, "account", StringComparison.OrdinalIgnoreCase)) return;
            if (context.Stage != 20) return;

            if (context.Depth > 1)
            {
                tracing?.Trace("AccountCreatePlugin: Skipping because Depth > 1");
                return;
            }

            if (!(context.InputParameters?.Contains("Target") == true && context.InputParameters["Target"] is Entity entity)) return;

            try
            {
                entity[DescriptionAttribute] = DescriptionText;
            }
            catch (Exception ex)
            {
                tracing?.Trace("AccountCreatePlugin failed: {0}", ex.ToString());
                throw new InvalidPluginExecutionException("AccountCreatePlugin failed. See trace for details.", ex);
            }
        }
    }
}
