using System;
using Microsoft.Xrm.Sdk;

namespace D365.Plugins
{
    public class AccountCreatePlugin : IPlugin
    {
        private const string DescriptionText = "This is a test description generated by PLugin";

        public void Execute(IServiceProvider serviceProvider)
        {
            if (serviceProvider == null) throw new ArgumentNullException(nameof(serviceProvider));

            var context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
            if (context?.InputParameters == null) return;

            if (!context.InputParameters.Contains("Target")) return;

            if (!(context.InputParameters["Target"] is Entity entity)) return;
            if (entity.LogicalName != "account") return;

            try
            {
                // For PreOperation stage: modifying the Target entity will be saved with the create operation.
                entity["description"] = DescriptionText;
            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException("AccountCreatePlugin failed: " + ex.Message, ex);
            }
        }
    }
}
