using FakeXrmEasy;
using Microsoft.Xrm.Sdk;
using Xunit;
using D365.Plugins;

namespace D365Plugins.Tests
{
    public class AccountCreatePluginTests
    {
        private const string ExpectedDescription = "This is a test description generated by Plugin";

        [Fact]
        public void SetsDescription_OnCreateAccount_Stage20_Depth1()
        {
            var ctx = new XrmFakedContext();
            var account = new Entity("account");
            var pluginContext = ctx.GetDefaultPluginContext();
            pluginContext.MessageName = "Create";
            pluginContext.PrimaryEntityName = "account";
            pluginContext.Stage = 20;
            pluginContext.Depth = 1;
            pluginContext.InputParameters["Target"] = account;

            ctx.ExecutePluginWith<AccountCreatePlugin>(pluginContext);

            Assert.True(account.Contains("description"));
            Assert.Equal(ExpectedDescription, account["description"]);
        }

        [Fact]
        public void DoesNotSetDescription_WhenNotCreate()
        {
            var ctx = new XrmFakedContext();
            var account = new Entity("account");
            var pluginContext = ctx.GetDefaultPluginContext();
            pluginContext.MessageName = "Update";
            pluginContext.PrimaryEntityName = "account";
            pluginContext.Stage = 20;
            pluginContext.Depth = 1;
            pluginContext.InputParameters["Target"] = account;

            ctx.ExecutePluginWith<AccountCreatePlugin>(pluginContext);

            Assert.False(account.Contains("description"));
        }

        [Fact]
        public void DoesNotSetDescription_WhenWrongEntityName()
        {
            var ctx = new XrmFakedContext();
            var contact = new Entity("contact");
            var pluginContext = ctx.GetDefaultPluginContext();
            pluginContext.MessageName = "Create";
            pluginContext.PrimaryEntityName = "contact";
            pluginContext.Stage = 20;
            pluginContext.Depth = 1;
            pluginContext.InputParameters["Target"] = contact;

            ctx.ExecutePluginWith<AccountCreatePlugin>(pluginContext);

            Assert.False(contact.Contains("description"));
        }

        [Fact]
        public void DoesNotSetDescription_WhenWrongStage()
        {
            var ctx = new XrmFakedContext();
            var account = new Entity("account");
            var pluginContext = ctx.GetDefaultPluginContext();
            pluginContext.MessageName = "Create";
            pluginContext.PrimaryEntityName = "account";
            pluginContext.Stage = 40;
            pluginContext.Depth = 1;
            pluginContext.InputParameters["Target"] = account;

            ctx.ExecutePluginWith<AccountCreatePlugin>(pluginContext);

            Assert.False(account.Contains("description"));
        }

        [Fact]
        public void DoesNotSetDescription_WhenDepthGreaterThanOne()
        {
            var ctx = new XrmFakedContext();
            var account = new Entity("account");
            var pluginContext = ctx.GetDefaultPluginContext();
            pluginContext.MessageName = "Create";
            pluginContext.PrimaryEntityName = "account";
            pluginContext.Stage = 20;
            pluginContext.Depth = 2;
            pluginContext.InputParameters["Target"] = account;

            ctx.ExecutePluginWith<AccountCreatePlugin>(pluginContext);

            Assert.False(account.Contains("description"));
        }

        [Fact]
        public void DoesNotThrow_WhenNoTargetParameter()
        {
            var ctx = new XrmFakedContext();
            var pluginContext = ctx.GetDefaultPluginContext();
            pluginContext.MessageName = "Create";
            pluginContext.PrimaryEntityName = "account";
            pluginContext.Stage = 20;
            pluginContext.Depth = 1;

            // Should not throw
            ctx.ExecutePluginWith<AccountCreatePlugin>(pluginContext);
        }
    }
}
